# Hello World Neural Network

Following a tutorial on building a Neral Network from scratch by: sentdex on YouTube

1. Following the first video on YT on the process, adding in my own changes for better and cleaner code

In [7]:
import sys
import numpy as np
import matplotlib as plt

import settings as vals

inputs = np.array(vals.INPUTS)
weights = [np.array(vals.WEIGHTS), np.array(vals.WEIGHTS_2), np.array(vals.WEIGHTS_3)]

biases = [vals.BIAS, vals.BIAS_2, vals.BIAS_3]

"""
    The Summantion of all inputs multiplied by all weights, then add the BIAS
"""
# output = [np.sum(inputs[0] * weights[0]) + bias[0], np.sum(inputs * weights[1]) + bias[1], np.sum(inputs * weights[2]) + bias[2]]

layer_outputs = []
for neuron_weights, neuron_bias in zip(weights, biases):
    neron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neron_output += n_input * weight
    neron_output += neuron_bias
    layer_outputs.append(neron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [4]:
"""
    With Dot products and layers
"""
import numpy as np
import settings as vals

inputs = [np.array(vals.INPUTS), np.array(vals.INPUTS_2), np.array(vals.INPUTS_3)]
weights = [np.array(vals.WEIGHTS), np.array(vals.WEIGHTS_2), np.array(vals.WEIGHTS_3)]
biases = [vals.BIAS, vals.BIAS_2, vals.BIAS_3]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_output = np.dot(inputs, np.array(weights).T) + biases
layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2

print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [7]:
"""
    Now with OOP and Dot Product to combine Layers
"""

import numpy as np
import settings as vals

np.random.seed(0)

# Using X as a symbols as the training data/data
X = [np.array(vals.INPUTS), np.array(vals.INPUTS_2), np.array(vals.INPUTS_3)]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)


[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [9]:
"""
    Rectified Linear Approach
"""

import numpy as np
import settings as vals

np.random.seed(0)

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

for i in inputs:
    output.append(max(0, i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [ ]:
import numpy as np
import settings as vals

np.random.seed(0)

# Using X as a symbols as the training data/data
X = [np.array(vals.INPUTS), np.array(vals.INPUTS_2), np.array(vals.INPUTS_3)]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)